### ISSUE TITLE
config +plusieurs erreurs

### ISSUE THREAD

**Issue by vz777** [thelia-modules/ElasticProduct#19]
Bonjour,
ce module fait très envie d'être utilisé ;)

J'ai bien vu qu'il est en dev mais je me dis que si j'ai fait remonter les erreur rencontrées, ça pourra sans doute faire avancer.

Je ne suis pas sur de la config qu'il faut mettre en bo, voila ce que j'ai fait :
 Hôte : localhost
Port : 9200
Nom d'utilisateur : elastic (valeur par défaut d'elasticsearch)
Mot de passe : changeme (valeur par défaut d'elasticsearch)
Prefixe de l'index : cequejeveux

Voici les erreurs que je rencontre en dev dans le bo :

-J'ai ce message qui s'affiche en bas de la page de config du module :
`') } else if (percent > 5) { document.getElementById("elastic_product_index_all_progress").style.width = percent+"%"; document.getElementById("elastic_product_index_all_progress").innerHTML = percent+"%"; } if(page '+jqXHR.statusText+'') } }); } $("#elastic_product_index_all").on('click', function (event) { document.getElementById("elastic_product_index_all_progress").style.width = "5%"; document.getElementById("elastic_product_index_all_progress").innerHTML = "5%"; $.get("https://www.grainedevie.net/index_dev.php/vzet23/module/ElasticProduct/index/create").success(function(response) { recursively_ajax(response.productCount); }); }) }); `
-Dans le console, j'ai deux fois `Uncaught SyntaxError: '' literal not terminated before end of script`

Lorsque j'essaie de construire l'index en ligne de commande, voila ce que j'ai :
`$ php Thelia elasticproduct:index:build
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/../../local/modules/VirtualProductControl/Config): failed to open dir: Too many open files in /home/../../core/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:52
Stack trace:
#0 /home/../../core/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(52): RecursiveDirectoryIterator->__construct('/home/../...', 4096)
#1 /home/../../core/vendor/symfony/finder/Finder.php(809): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('/home/../...', 4096, false)
#2 /home/../../core/vendor/symfony/finder/Finder.php(687): Symfony\Component\Finder\Finder->searchInDirectory('/home/../...')
#3 /home/../../core/lib/Thelia/Module/ModuleManagement.php(63): Symfony\Component\Finder\Finder->getIterator()
#4 /home/../../core/lib/Thelia/Core/Thelia.php(177): Thelia\Module\ModuleManagement->updateModules(Object(CoreDevDebugProject in/home/../../core/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 52`

**Comment by lopes-vincent** [comment]
Bonjour,

Est-ce que vous respectez bien les prérequis du module pour la partie ElasticSearch :
* ElasticSearch
    * Version: >= 6.4 < 7.0
    * Plugins:
        - analysis-icu

**Comment by vz777** [comment]
Bonjour,
en effet, je n'avais pas fait attention à ces lignes, dsl ...

J'ai été voir, j'en déduis qu'il faut installer java,
aussi je ne sais pas si je vais pouvoir installer ElasticSearch sur mon mutualisé.
Je vois avec l'hébergeur.

Mais j'ai l'impression qu'il faut un dedié ...

**Comment by vz777** [comment]
ok bon ben c'est mort impossible d'installer java sur le server ou je suis,
je vais voir avec doofinder ou autre système.

Ptet à préciser dans le readme qu'il faut java et que c'est quasi impossible en mutu ? 
En mm tps c'est préciser dans la doc d'elasticsearch

Désolé pour le dérangement
