### ISSUE TITLE
I need help to use module with DE langauge

### ISSUE THREAD

**Issue by cristelucian** [thelia-modules/ElasticProduct#3]
Hello, what changes I have to add to use DE language beside EN and FR?

**Comment by lopes-vincent** [comment]
Hi, 

You need to add a new analyzer, I added a basic one for you in this commit https://github.com/thelia-modules/ElasticProduct/commit/162a4305734dcca2ab53c3507a7f5d75e1d963ce
You just need to update your module.

The analyzer maybe need to be adapted to german language to get an optimized research, I can't do it as I don't know this language but if you do it please feel free to make a pull request on this repository and I will merge it with pleasure !

**Comment by cristelucian** [comment]
Thanks! working as expected!
